repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        args:
        - bot
        language_version: python3
  - repo: local
    hooks:
      - id: pylint
        args:
        - bot
        name: pylint
        entry: pipenv run pylint
        language: system
        types: [python]
