version: "3.7"
services:
  gurkbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gurkbot
    init: true

    restart: always

    environment:
      - TOKEN
      - PREFIX
      - CHANNEL_DEVLOG

    volumes:
      - .:/bot
